### ISSUE TITLE
Add pagination to followers/following

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#48]
A la /users/ paginator

Perhaps only dispal **n of N** if more than 1 page exists, on both /users/ and /followers|following/

**Comment by juliasolorzano** [comment]
@daaray I'd like to propose that we move this and all pagination into Phase 2 of this project. I think it's a great idea, but want to make sure that we get our other tasks completed before moving into this. 

I'd also like to discuss IRL how to best approach pagination. Since we are developing for mobile first, doing the traditional method of pagination is probably not the best solution. Let's talk more about this! It'd be great to include if we have time in Phase 1.
