### ISSUE TITLE
Featured image upload fails when image is too large

### ISSUE THREAD

**Issue by juliasolorzano** [python/raspberryio#62]
We should probably determine how large the files can be when the user uploads them. I've attached the error I received on staging when trying to upload a 1.6MB jpg. Not sure what the limitations will be on production.

![Screen Shot 2013-02-15 at 12 17 20 AM](https://f.cloud.github.com/assets/955558/159524/130f1d7c-772f-11e2-8ca3-52f580a75faf.png)

**Comment by calebsmith** [comment]
I'm not sure yet if it is the best option, but I think we should investigate using the jQuery file uploader currently in use for the ProjectStep gallery here.

We might need to tweak things a bit so that you can only add one image and we probably don't need an AJAX solution. Considering that, this might be more work than is needed, but I'd like to figure out a client side solution for scaling the image down to a more appropriate size.

**Comment by calebsmith** [comment]
Just to clarify, this problem results because nginx is configured to have a hard limit for the uploads it will except

**Comment by juliasolorzano** [comment]
@calebsmith maybe a fast solve would it be to add some help text, clarifying to the user what the size limitation is. It would also be good to decide a width/height limitation too.

**Comment by calebsmith** [comment]
That sounds good to me too. The nginx error page is pretty scary looking. I don't think most users would think "Oh my image is too big"

**Comment by daaray** [comment]
Change was made to allow for 5MB uploads...we'll have to see how this plays out with usability & load.

I updated my avatar with a 3MB image and it took 10 seconds to upload.

**Comment by gsaines** [comment]
Based on our discussion earlier today cementing the 5MB limit, can this be closed, or is there additional work left to be done?

**Comment by juliasolorzano** [comment]
@gsaines closing this ticket, as #101 will resolve any issues with image sizing.

**Comment by proy87** [comment]
As a dirty workaround, resize image using [ https://imagechanger.net](https://imagechanger.net)
